coverage:
  status:
    project:
      default:
        target: 68%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "cmd/**"
  - "tools/**"
  - "benchmark/**"
