coverage:
  range: "50...75"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 10%

ignore:
  - "cmd/**"
  - "tools/**"
  - "benchmark/**"
