server_name __DOMAIN__;
client_max_body_size 16m;
root /var/www/html;

ssl_certificate /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;

location / {
    try_files $uri $uri/ /index.html;
}
