#!/bin/sh
set -eu

gateway_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
state_root="$gateway_root/state"
domain=
email=
carrier=https-lanes
telego_image=scratchnet/telego:latest
web_enabled=true
mtproxy_port=443
internal_mtproxy_port=9443

usage() {
    printf '%s\n' \
        "Usage: ./setup.sh --domain HOSTNAME --email ADDRESS [options]" \
        "" \
        "Options:" \
        "  --mtproxy-port PORT  Public MTProxy port (default: 443)" \
        "  --no-web             Disable the Telegram WEB proxy" \
        "  --carrier MODE       https, https-lanes, websocket, or websocket-lanes" \
        "  --image IMAGE        Telego image (default: scratchnet/telego:latest)" \
        "  --help               Show this help"
}

fail() {
    printf 'Error: %s\n' "$1" >&2
    exit 1
}

progress() {
    printf '\n==> %s\n' "$1"
}

detail() {
    printf '    %s\n' "$1"
}

need_value() {
    if [ "$#" -lt 2 ] || [ -z "$2" ]; then
        fail "$1 requires a value"
    fi
}

valid_hostname() {
    gateway_hostname=$1
    if [ -z "$gateway_hostname" ] || [ "${#gateway_hostname}" -gt 253 ]; then
        return 1
    fi
    case "$gateway_hostname" in
        *[!a-z0-9.-]* | .* | *. | *..*) return 1 ;;
        *.*) ;;
        *) return 1 ;;
    esac

    gateway_old_ifs=$IFS
    IFS=.
    set -- $gateway_hostname
    IFS=$gateway_old_ifs
    for gateway_label do
        if [ -z "$gateway_label" ] || [ "${#gateway_label}" -gt 63 ]; then
            return 1
        fi
        case "$gateway_label" in
            -* | *-) return 1 ;;
        esac
    done

    case "$gateway_label" in
        0x*)
            gateway_numeric_suffix=${gateway_label#0x}
            case "$gateway_numeric_suffix" in
                *[!0-9a-f]*) ;;
                *) return 1 ;;
            esac
            ;;
        *[!0-9]*) ;;
        *) return 1 ;;
    esac
}

valid_port() {
    gateway_port=$1
    case "$gateway_port" in
        '' | *[!0-9]* | 0 | 0* | ??????*) return 1 ;;
    esac
    [ "$gateway_port" -le 65535 ]
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --domain)
            need_value "$@"
            domain=$2
            shift 2
            ;;
        --email)
            need_value "$@"
            email=$2
            shift 2
            ;;
        --carrier)
            need_value "$@"
            carrier=$2
            shift 2
            ;;
        --mtproxy-port)
            need_value "$@"
            mtproxy_port=$2
            shift 2
            ;;
        --no-web)
            web_enabled=false
            shift
            ;;
        --image)
            need_value "$@"
            telego_image=$2
            shift 2
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            fail "unknown option: $1"
            ;;
    esac
done

if ! valid_hostname "$domain"; then
    fail "--domain must be a lowercase DNS hostname"
fi
if ! valid_port "$mtproxy_port"; then
    fail "--mtproxy-port must be an integer from 1 through 65535"
fi
if [ "$mtproxy_port" -eq 80 ]; then
    fail "--mtproxy-port cannot use port 80 because certificate renewal requires it"
fi
case "$email" in
    *@*.*) ;;
    *) fail "--email must be a valid email address" ;;
esac
case "$email" in
    *[!A-Za-z0-9._+@-]*) fail "--email contains an unsupported character" ;;
esac
case "$carrier" in
    https | https-lanes | websocket | websocket-lanes) ;;
    *) fail "--carrier has an unsupported value" ;;
esac
case "$telego_image" in
    '' | *[!A-Za-z0-9._/:@-]*) fail "--image contains an unsupported character" ;;
esac

progress "Installation plan"
detail "Domain: $domain"
if [ "$web_enabled" = true ]; then
    detail "WEB endpoint: $domain:443 ($carrier carrier)"
else
    detail "WEB proxy: disabled"
fi
detail "MTProxy endpoint: $domain:$mtproxy_port"
detail "Persistent state: $state_root"

progress "Docker availability"
command -v docker >/dev/null 2>&1 || fail "docker is not installed"
docker compose version >/dev/null 2>&1 || fail "Docker Compose is not available"
docker info >/dev/null 2>&1 || fail "the Docker daemon is not available"
detail "Docker Engine and Docker Compose are available."

progress "Preparing persistent storage"
umask 077
mkdir -p \
    "$state_root/telego" \
    "$state_root/nginx" \
    "$state_root/site" \
    "$state_root/letsencrypt/conf" \
    "$state_root/letsencrypt/lib" \
    "$state_root/letsencrypt/www" \
    "$state_root/runtime"
detail "Gateway state stays in $state_root."

domain_file="$state_root/domain"
carrier_file="$state_root/carrier"
config_file="$state_root/telego/config.toml"
web_enabled_file="$state_root/web-enabled"
mtproxy_port_file="$state_root/mtproxy-port"
internal_mtproxy_port_file="$state_root/internal-mtproxy-port"
gateway_server_file="$state_root/nginx/gateway-server.conf"
compose_override_file="$gateway_root/compose.override.yaml"
compose_override_marker='# Generated by the Telego managed gateway. Do not edit.'
legacy_layout=false

if [ -f "$compose_override_file" ]; then
    IFS= read -r configured_override_marker < "$compose_override_file"
    if [ "$configured_override_marker" != "$compose_override_marker" ]; then
        fail "compose.override.yaml exists and is not managed by this setup script"
    fi
fi

if [ -f "$config_file" ] && [ ! -f "$web_enabled_file" ] && [ ! -f "$mtproxy_port_file" ]; then
    if [ "$web_enabled" != true ] || [ "$mtproxy_port" -ne 443 ]; then
        fail "an existing gateway from an older installer supports only WEB and MTProxy on port 443"
    fi
    legacy_layout=true
    internal_mtproxy_port=443
fi
if [ -f "$config_file" ] && { [ ! -f "$web_enabled_file" ] || [ ! -f "$mtproxy_port_file" ]; } && [ "$legacy_layout" != true ]; then
    fail "the gateway mode state is incomplete"
fi

if [ -f "$domain_file" ]; then
    IFS= read -r configured_domain < "$domain_file"
    if [ "$configured_domain" != "$domain" ]; then
        fail "state belongs to domain $configured_domain"
    fi
fi
if [ -f "$web_enabled_file" ]; then
    IFS= read -r configured_web_enabled < "$web_enabled_file"
    if [ "$configured_web_enabled" != "$web_enabled" ]; then
        fail "state uses web-enabled=$configured_web_enabled"
    fi
fi
if [ -f "$mtproxy_port_file" ]; then
    IFS= read -r configured_mtproxy_port < "$mtproxy_port_file"
    if [ "$configured_mtproxy_port" != "$mtproxy_port" ]; then
        fail "state uses MTProxy port $configured_mtproxy_port"
    fi
fi
if [ -f "$internal_mtproxy_port_file" ]; then
    IFS= read -r internal_mtproxy_port < "$internal_mtproxy_port_file"
    if ! valid_port "$internal_mtproxy_port"; then
        fail "the internal MTProxy port state is invalid"
    fi
fi
if [ "$web_enabled" = true ] && [ -f "$carrier_file" ]; then
    IFS= read -r configured_carrier < "$carrier_file"
    if [ "$configured_carrier" != "$carrier" ]; then
        fail "state uses carrier $configured_carrier"
    fi
fi

if [ ! -f "$config_file" ]; then
    progress "Creating the gateway configuration"
    gateway_secret=$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')
    if [ "${#gateway_secret}" -ne 32 ]; then
        fail "secret generation failed"
    fi

    config_temp=$(mktemp "$state_root/telego/config.toml.XXXXXX")
    nginx_temp=$(mktemp "$state_root/nginx/nginx.conf.XXXXXX")
    gateway_server_temp=$(mktemp "$state_root/nginx/gateway-server.conf.XXXXXX")

    telego_template="$gateway_root/templates/telego.toml"
    nginx_server_template="$gateway_root/templates/nginx-web-server.conf"
    if [ "$web_enabled" != true ]; then
        telego_template="$gateway_root/templates/mtproxy.toml"
        nginx_server_template="$gateway_root/templates/nginx-site-server.conf"
    fi

    sed \
        -e "s|__DOMAIN__|$domain|g" \
        -e "s|__SECRET__|$gateway_secret|g" \
        -e "s|__CARRIER__|$carrier|g" \
        "$telego_template" > "$config_temp"
    sed \
        -e "s|__DOMAIN__|$domain|g" \
        "$gateway_root/templates/nginx.conf" > "$nginx_temp"
    sed \
        -e "s|__DOMAIN__|$domain|g" \
        "$nginx_server_template" > "$gateway_server_temp"

    mv "$config_temp" "$config_file"
    mv "$nginx_temp" "$state_root/nginx/nginx.conf"
    mv "$gateway_server_temp" "$gateway_server_file"
    cp "$gateway_root/templates/index.html" "$state_root/site/index.html"
    printf '%s\n' "$domain" > "$domain_file"
    printf '%s\n' "$web_enabled" > "$web_enabled_file"
    printf '%s\n' "$mtproxy_port" > "$mtproxy_port_file"
    printf '%s\n' "$internal_mtproxy_port" > "$internal_mtproxy_port_file"
    if [ "$web_enabled" = true ]; then
        printf '%s\n' "$carrier" > "$carrier_file"
    fi

    hostname_hex=$(printf '%s' "$domain" | od -An -tx1 | tr -d ' \n')
    ee_secret="ee$gateway_secret$hostname_hex"
    dd_secret="dd$gateway_secret"
    {
        printf '%s\n' \
            "tg://proxy?server=$domain&port=$mtproxy_port&secret=$ee_secret" \
            "tg://proxy?server=$domain&port=$mtproxy_port&secret=$dd_secret"
        if [ "$web_enabled" = true ]; then
            printf '%s\n' \
                "tg://webproxy?server=$domain&secret=$gateway_secret" \
                "https://t.me/webproxy?server=$domain&secret=$gateway_secret" \
                "tg://webproxy?server=$domain&secret=$dd_secret" \
                "https://t.me/webproxy?server=$domain&secret=$dd_secret"
        fi
    } > "$state_root/links.txt"

    chmod 600 "$config_file" "$state_root/links.txt"
    chmod 644 \
        "$state_root/nginx/nginx.conf" \
        "$gateway_server_file" \
        "$state_root/site/index.html"
    detail "Telego configuration: $config_file"
    detail "Nginx listeners: $state_root/nginx/nginx.conf"
    detail "Nginx request routing: $gateway_server_file"
    detail "Ordinary website: $state_root/site/index.html"
    detail "Client links: $state_root/links.txt"
else
    progress "Using the existing gateway configuration"
    detail "The setup keeps the Telego configuration and proxy secret."
    detail "Telego configuration: $config_file"
    detail "Nginx listeners: $state_root/nginx/nginx.conf"
    detail "Nginx request routing: $gateway_server_file"
    detail "Ordinary website: $state_root/site/index.html"
    detail "Client links: $state_root/links.txt"
    if [ "$legacy_layout" = true ]; then
        detail "The existing gateway uses the legacy shared-port layout."
    fi
fi

if [ ! -f "$gateway_server_file" ]; then
    sed \
        -e "s|__DOMAIN__|$domain|g" \
        "$gateway_root/templates/nginx-web-server.conf" > "$gateway_server_file"
    chmod 644 "$gateway_server_file"
fi

progress "Refreshing managed helper files"
cp "$gateway_root/nginx/watch-certificate.sh" "$state_root/nginx/watch-certificate.sh"
chmod 755 \
    "$state_root/site" \
    "$state_root/letsencrypt/www" \
    "$state_root/nginx/watch-certificate.sh"

printf '%s\n' "TELEGO_IMAGE=$telego_image" > "$gateway_root/.env"
detail "Certificate reload helper: $state_root/nginx/watch-certificate.sh"
detail "Telego image selection: $gateway_root/.env"

progress "Writing public port mappings"
compose_override_temp=$(mktemp "$gateway_root/compose.override.yaml.XXXXXX")
if [ "$mtproxy_port" -eq 443 ]; then
    printf '%s\n' \
        "$compose_override_marker" \
        'services:' \
        '  nginx:' \
        '    ports:' \
        '      - "80:80"' \
        "      - \"443:$internal_mtproxy_port\"" \
        > "$compose_override_temp"
else
    printf '%s\n' \
        "$compose_override_marker" \
        'services:' \
        '  nginx:' \
        '    ports:' \
        '      - "80:80"' \
        '      - "443:443"' \
        "      - \"$mtproxy_port:$internal_mtproxy_port\"" \
        > "$compose_override_temp"
fi
chmod 644 "$compose_override_temp"
mv "$compose_override_temp" "$compose_override_file"
detail "Docker mapping file: $compose_override_file"
detail "Public TCP 80 -> Nginx 80 for certificate creation and renewal."
if [ "$mtproxy_port" -eq 443 ]; then
    if [ "$web_enabled" = true ]; then
        detail "Public TCP 443 -> Telego $internal_mtproxy_port for MTProxy and WEB traffic."
    else
        detail "Public TCP 443 -> Telego $internal_mtproxy_port for MTProxy and website probes."
    fi
else
    if [ "$web_enabled" = true ]; then
        detail "Public TCP 443 -> Nginx 443 for WEB and website traffic."
    else
        detail "Public TCP 443 -> Nginx 443 for website traffic."
    fi
    detail "Public TCP $mtproxy_port -> Telego $internal_mtproxy_port for MTProxy traffic."
fi

cd "$gateway_root"
progress "Docker configuration"
docker compose config --quiet
detail "Docker Compose accepted the generated configuration."

certificate_root="$state_root/letsencrypt/conf/live/$domain"
progress "Preparing the TLS certificate"
if [ ! -s "$certificate_root/fullchain.pem" ] || [ ! -s "$certificate_root/privkey.pem" ]; then
    detail "No certificate exists in $certificate_root."
    detail "Certbot uses public TCP port 80 to request the first certificate."
    docker compose --profile setup run --rm -p 80:80 certbot-init \
        certonly --standalone --non-interactive --agree-tos \
        --email "$email" -d "$domain"
    if [ ! -s "$certificate_root/fullchain.pem" ] || [ ! -s "$certificate_root/privkey.pem" ]; then
        fail "Certbot did not create the required certificate files"
    fi
    detail "Certbot stored the certificate in $certificate_root."
else
    detail "Using the existing certificate in $certificate_root."
fi

progress "Starting Nginx"
detail "Nginx provides TLS, the ordinary website, and certificate renewal routing."
docker compose up -d nginx
progress "Nginx configuration"
docker compose exec -T nginx nginx -t
detail "Nginx accepted the generated configuration."
progress "Starting Telego and certificate renewal"
docker compose up -d
progress "Current service state"
docker compose ps

printf '\nPublic endpoints:\n'
if [ "$web_enabled" = true ]; then
    printf '  WEB:      %s:443\n' "$domain"
else
    printf '  Website:  %s:443\n' "$domain"
fi
printf '  MTProxy:  %s:%s\n' "$domain" "$mtproxy_port"
if [ "$mtproxy_port" -eq 443 ]; then
    printf '  Firewall: permit inbound TCP ports 80 and 443\n'
else
    printf '  Firewall: permit inbound TCP ports 80, 443, and %s\n' "$mtproxy_port"
fi
printf '\nProxy links:\n'
sed 's/^/  /' "$state_root/links.txt"
printf '\nState directory: %s\n' "$state_root"
printf 'Logs: docker compose logs -f nginx telego certbot\n'
